### PR TITLE
Fix repo URL in package.json

### PR DESCRIPTION
**Pull request by cdeil**

### CODE REVIEW

**Comment by ebertin** [comment]
Hi Christoph,
Thanks and Happy New Year! I am about to commit a large revision of VisiOmatic together with documentation (development went private for a while for no real reason). I hope to have that done in the coming days)

**Comment by cdeil** [comment]
@ebertin - Happy new year to you as well!

That sounds great!

I just started looking at the visiomatic source 5 min ago and ran into this:

```
$ npm install
npm WARN engine karma@0.8.8: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"5.3.0","npm":"3.3.12"})
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! No compatible version found: jquery-browser@~1.10
npm ERR! Valid install targets:
npm ERR! 2.0.0-1, 1.10.2-1, 1.9.1-1, 1.8.2-1, 1.7.2-3, 1.7.2-2, 1.7.2-1, 1.7.1-2, 1.7.1-1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deil/code/visiomatic/npm-debug.log
```

But if it's just a few days, I'll wait for your update and then start looking in detail how it works.

Concerning the documentation - could you please put it in this repo? Having it only at http://www.astromatic.net/software/visiomatic means that it's not possible to contribute.
I've set up Sphinx docs on readthedocs for several packages (example: http://astroplan.readthedocs.org/en/latest/), so just in case RST / Sphinx is something you're considering for high-level docs, I'd be happy to help out with this.

**Comment by ebertin** [comment]
Yup, one can now use the 'jquery' package. This is fixed in VisiOmatic 2.0.
And yes, the doc will be on GitHub as a doc/ subdir (and readable through ReadTheDocs). Just working on it at this time!

**Comment by cdeil** [comment]
:smile: 

One more thing: our FITS survey images are CAR projection. Will this be available?
Or is this something that should be implemented?
Is it possible to re-use https://github.com/astrojs/wcsjs and wrap it or re-implement from scratch to make all FITS projections available with the visiomatic Leaflet viewer?

**Comment by ebertin** [comment]
Yes CAR is in there.
It may be possible to re-use https://github.com/astrojs/wcsjs but honestly I don't know how this could be done.

**Pull request merged**
